export const FETCHING_COUNTRIES = "FETCHING_COUNTRIES";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
export const FETCH_COUNTRIES_ERROR = "FETCH_COUNTRIES_ERROR";

//
export const FETCHING_COUNTRY = "FETCH_COUNTRY";
export const FETCH_COUNTRY_SUCCESS = "FETCH_COUNTRY_SUCCESS";
export const FETCH_COUNTRY_ERROR = "FETCH_COUNTRY_ERROR";

//
export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";

//
export const NO_SORT = "NO_SORT";
export const SORT_NAME_ASC = "SORT_NAME_ASC";
export const SORT_NAME_DES = "SORT_NAME_DES";
export const SORT_POPULATION_ASC = "SORT_POPULATION_ASC";
export const SORT_POPULATION_DES = "SORT_POPULATION_DES";
export const SORT_REGION_ASC = "SORT_REGION_ASC";
export const SORT_REGION_DES = "SORT_REGION_DES";
